#!/bin/bash
set -e

WASM_HOME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHARLS_INCL_DIR=$WASM_HOME_DIR/lib/charls-2.3.4/include
CHARLS_SRC_DIR=$WASM_HOME_DIR/lib/charls-2.3.4/src
OPENJPEG_SRC_DIR=$WASM_HOME_DIR/lib/openjpeg-2.5.0
LIBIJG8_SRC_DIR=$WASM_HOME_DIR/lib/libijg8-6b
LIBIJG12_SRC_DIR=$WASM_HOME_DIR/lib/libijg12-6b
LIBIJG16_SRC_DIR=$WASM_HOME_DIR/lib/libijg16-6b
WASM_SRC_DIR=$WASM_HOME_DIR/src

c_files=(
    # openjpeg
    "$OPENJPEG_SRC_DIR/thread.c"
    "$OPENJPEG_SRC_DIR/bio.c"
    "$OPENJPEG_SRC_DIR/cio.c"
    "$OPENJPEG_SRC_DIR/dwt.c"
    "$OPENJPEG_SRC_DIR/event.c"
    "$OPENJPEG_SRC_DIR/ht_dec.c"
    "$OPENJPEG_SRC_DIR/image.c"
    "$OPENJPEG_SRC_DIR/invert.c"
    "$OPENJPEG_SRC_DIR/j2k.c"
    "$OPENJPEG_SRC_DIR/jp2.c"
    "$OPENJPEG_SRC_DIR/mct.c"
    "$OPENJPEG_SRC_DIR/mqc.c"
    "$OPENJPEG_SRC_DIR/openjpeg.c"
    "$OPENJPEG_SRC_DIR/opj_clock.c"
    "$OPENJPEG_SRC_DIR/pi.c"
    "$OPENJPEG_SRC_DIR/t1.c"
    "$OPENJPEG_SRC_DIR/t2.c"
    "$OPENJPEG_SRC_DIR/tcd.c"
    "$OPENJPEG_SRC_DIR/tgt.c"
    "$OPENJPEG_SRC_DIR/function_list.c"
    "$OPENJPEG_SRC_DIR/opj_malloc.c"
    "$OPENJPEG_SRC_DIR/sparse_array.c"

    # libijg8
    "$LIBIJG8_SRC_DIR/jaricom.c"
    "$LIBIJG8_SRC_DIR/jcapimin.c"
    "$LIBIJG8_SRC_DIR/jcapistd.c"
    "$LIBIJG8_SRC_DIR/jcarith.c"
    "$LIBIJG8_SRC_DIR/jccoefct.c"
    "$LIBIJG8_SRC_DIR/jccolor.c"
    "$LIBIJG8_SRC_DIR/jcdctmgr.c"
    "$LIBIJG8_SRC_DIR/jcdiffct.c"
    "$LIBIJG8_SRC_DIR/jchuff.c"
    "$LIBIJG8_SRC_DIR/jcinit.c"
    "$LIBIJG8_SRC_DIR/jclhuff.c"
    "$LIBIJG8_SRC_DIR/jclossls.c"
    "$LIBIJG8_SRC_DIR/jclossy.c"
    "$LIBIJG8_SRC_DIR/jcmainct.c"
    "$LIBIJG8_SRC_DIR/jcmarker.c"
    "$LIBIJG8_SRC_DIR/jcmaster.c"
    "$LIBIJG8_SRC_DIR/jcodec.c"
    "$LIBIJG8_SRC_DIR/jcomapi.c"
    "$LIBIJG8_SRC_DIR/jcparam.c"
    "$LIBIJG8_SRC_DIR/jcphuff.c"
    "$LIBIJG8_SRC_DIR/jcpred.c"
    "$LIBIJG8_SRC_DIR/jcprepct.c"
    "$LIBIJG8_SRC_DIR/jcsample.c"
    "$LIBIJG8_SRC_DIR/jcscale.c"
    "$LIBIJG8_SRC_DIR/jcshuff.c"
    "$LIBIJG8_SRC_DIR/jctrans.c"
    "$LIBIJG8_SRC_DIR/jdapimin.c"
    "$LIBIJG8_SRC_DIR/jdapistd.c"
    "$LIBIJG8_SRC_DIR/jdarith.c"
    "$LIBIJG8_SRC_DIR/jdatadst.c"
    "$LIBIJG8_SRC_DIR/jdatasrc.c"
    "$LIBIJG8_SRC_DIR/jdcoefct.c"
    "$LIBIJG8_SRC_DIR/jdcolor.c"
    "$LIBIJG8_SRC_DIR/jddctmgr.c"
    "$LIBIJG8_SRC_DIR/jddiffct.c"
    "$LIBIJG8_SRC_DIR/jdhuff.c"
    "$LIBIJG8_SRC_DIR/jdinput.c"
    "$LIBIJG8_SRC_DIR/jdlhuff.c"
    "$LIBIJG8_SRC_DIR/jdlossls.c"
    "$LIBIJG8_SRC_DIR/jdlossy.c"
    "$LIBIJG8_SRC_DIR/jdmainct.c"
    "$LIBIJG8_SRC_DIR/jdmarker.c"
    "$LIBIJG8_SRC_DIR/jdmaster.c"
    "$LIBIJG8_SRC_DIR/jdmerge.c"
    "$LIBIJG8_SRC_DIR/jdphuff.c"
    "$LIBIJG8_SRC_DIR/jdpostct.c"
    "$LIBIJG8_SRC_DIR/jdpred.c"
    "$LIBIJG8_SRC_DIR/jdsample.c"
    "$LIBIJG8_SRC_DIR/jdscale.c"
    "$LIBIJG8_SRC_DIR/jdshuff.c"
    "$LIBIJG8_SRC_DIR/jdtrans.c"
    "$LIBIJG8_SRC_DIR/jerror.c"
    "$LIBIJG8_SRC_DIR/jfdctflt.c"
    "$LIBIJG8_SRC_DIR/jfdctfst.c"
    "$LIBIJG8_SRC_DIR/jfdctint.c"
    "$LIBIJG8_SRC_DIR/jidctflt.c"
    "$LIBIJG8_SRC_DIR/jidctfst.c"
    "$LIBIJG8_SRC_DIR/jidctint.c"
    "$LIBIJG8_SRC_DIR/jidctred.c"
    "$LIBIJG8_SRC_DIR/jmemmgr.c"
    "$LIBIJG8_SRC_DIR/jmemnobs.c"
    "$LIBIJG8_SRC_DIR/jquant1.c"
    "$LIBIJG8_SRC_DIR/jquant2.c"
    "$LIBIJG8_SRC_DIR/jutils.c"

    # libijg12
    "$LIBIJG12_SRC_DIR/jaricom.c"
    "$LIBIJG12_SRC_DIR/jcapimin.c"
    "$LIBIJG12_SRC_DIR/jcapistd.c"
    "$LIBIJG12_SRC_DIR/jcarith.c"
    "$LIBIJG12_SRC_DIR/jccoefct.c"
    "$LIBIJG12_SRC_DIR/jccolor.c"
    "$LIBIJG12_SRC_DIR/jcdctmgr.c"
    "$LIBIJG12_SRC_DIR/jcdiffct.c"
    "$LIBIJG12_SRC_DIR/jchuff.c"
    "$LIBIJG12_SRC_DIR/jcinit.c"
    "$LIBIJG12_SRC_DIR/jclhuff.c"
    "$LIBIJG12_SRC_DIR/jclossls.c"
    "$LIBIJG12_SRC_DIR/jclossy.c"
    "$LIBIJG12_SRC_DIR/jcmainct.c"
    "$LIBIJG12_SRC_DIR/jcmarker.c"
    "$LIBIJG12_SRC_DIR/jcmaster.c"
    "$LIBIJG12_SRC_DIR/jcodec.c"
    "$LIBIJG12_SRC_DIR/jcomapi.c"
    "$LIBIJG12_SRC_DIR/jcparam.c"
    "$LIBIJG12_SRC_DIR/jcphuff.c"
    "$LIBIJG12_SRC_DIR/jcpred.c"
    "$LIBIJG12_SRC_DIR/jcprepct.c"
    "$LIBIJG12_SRC_DIR/jcsample.c"
    "$LIBIJG12_SRC_DIR/jcscale.c"
    "$LIBIJG12_SRC_DIR/jcshuff.c"
    "$LIBIJG12_SRC_DIR/jctrans.c"
    "$LIBIJG12_SRC_DIR/jdapimin.c"
    "$LIBIJG12_SRC_DIR/jdapistd.c"
    "$LIBIJG12_SRC_DIR/jdarith.c"
    "$LIBIJG12_SRC_DIR/jdatadst.c"
    "$LIBIJG12_SRC_DIR/jdatasrc.c"
    "$LIBIJG12_SRC_DIR/jdcoefct.c"
    "$LIBIJG12_SRC_DIR/jdcolor.c"
    "$LIBIJG12_SRC_DIR/jddctmgr.c"
    "$LIBIJG12_SRC_DIR/jddiffct.c"
    "$LIBIJG12_SRC_DIR/jdhuff.c"
    "$LIBIJG12_SRC_DIR/jdinput.c"
    "$LIBIJG12_SRC_DIR/jdlhuff.c"
    "$LIBIJG12_SRC_DIR/jdlossls.c"
    "$LIBIJG12_SRC_DIR/jdlossy.c"
    "$LIBIJG12_SRC_DIR/jdmainct.c"
    "$LIBIJG12_SRC_DIR/jdmarker.c"
    "$LIBIJG12_SRC_DIR/jdmaster.c"
    "$LIBIJG12_SRC_DIR/jdmerge.c"
    "$LIBIJG12_SRC_DIR/jdphuff.c"
    "$LIBIJG12_SRC_DIR/jdpostct.c"
    "$LIBIJG12_SRC_DIR/jdpred.c"
    "$LIBIJG12_SRC_DIR/jdsample.c"
    "$LIBIJG12_SRC_DIR/jdscale.c"
    "$LIBIJG12_SRC_DIR/jdshuff.c"
    "$LIBIJG12_SRC_DIR/jdtrans.c"
    "$LIBIJG12_SRC_DIR/jerror.c"
    "$LIBIJG12_SRC_DIR/jfdctflt.c"
    "$LIBIJG12_SRC_DIR/jfdctfst.c"
    "$LIBIJG12_SRC_DIR/jfdctint.c"
    "$LIBIJG12_SRC_DIR/jidctflt.c"
    "$LIBIJG12_SRC_DIR/jidctfst.c"
    "$LIBIJG12_SRC_DIR/jidctint.c"
    "$LIBIJG12_SRC_DIR/jidctred.c"
    "$LIBIJG12_SRC_DIR/jmemmgr.c"
    "$LIBIJG12_SRC_DIR/jmemnobs.c"
    "$LIBIJG12_SRC_DIR/jquant1.c"
    "$LIBIJG12_SRC_DIR/jquant2.c"
    "$LIBIJG12_SRC_DIR/jutils.c"

    # libijg16
    "$LIBIJG16_SRC_DIR/jaricom.c"
    "$LIBIJG16_SRC_DIR/jcapimin.c"
    "$LIBIJG16_SRC_DIR/jcapistd.c"
    "$LIBIJG16_SRC_DIR/jcarith.c"
    "$LIBIJG16_SRC_DIR/jccoefct.c"
    "$LIBIJG16_SRC_DIR/jccolor.c"
    "$LIBIJG16_SRC_DIR/jcdctmgr.c"
    "$LIBIJG16_SRC_DIR/jcdiffct.c"
    "$LIBIJG16_SRC_DIR/jchuff.c"
    "$LIBIJG16_SRC_DIR/jcinit.c"
    "$LIBIJG16_SRC_DIR/jclhuff.c"
    "$LIBIJG16_SRC_DIR/jclossls.c"
    "$LIBIJG16_SRC_DIR/jclossy.c"
    "$LIBIJG16_SRC_DIR/jcmainct.c"
    "$LIBIJG16_SRC_DIR/jcmarker.c"
    "$LIBIJG16_SRC_DIR/jcmaster.c"
    "$LIBIJG16_SRC_DIR/jcodec.c"
    "$LIBIJG16_SRC_DIR/jcomapi.c"
    "$LIBIJG16_SRC_DIR/jcparam.c"
    "$LIBIJG16_SRC_DIR/jcphuff.c"
    "$LIBIJG16_SRC_DIR/jcpred.c"
    "$LIBIJG16_SRC_DIR/jcprepct.c"
    "$LIBIJG16_SRC_DIR/jcsample.c"
    "$LIBIJG16_SRC_DIR/jcscale.c"
    "$LIBIJG16_SRC_DIR/jcshuff.c"
    "$LIBIJG16_SRC_DIR/jctrans.c"
    "$LIBIJG16_SRC_DIR/jdapimin.c"
    "$LIBIJG16_SRC_DIR/jdapistd.c"
    "$LIBIJG16_SRC_DIR/jdarith.c"
    "$LIBIJG16_SRC_DIR/jdatadst.c"
    "$LIBIJG16_SRC_DIR/jdatasrc.c"
    "$LIBIJG16_SRC_DIR/jdcoefct.c"
    "$LIBIJG16_SRC_DIR/jdcolor.c"
    "$LIBIJG16_SRC_DIR/jddctmgr.c"
    "$LIBIJG16_SRC_DIR/jddiffct.c"
    "$LIBIJG16_SRC_DIR/jdhuff.c"
    "$LIBIJG16_SRC_DIR/jdinput.c"
    "$LIBIJG16_SRC_DIR/jdlhuff.c"
    "$LIBIJG16_SRC_DIR/jdlossls.c"
    "$LIBIJG16_SRC_DIR/jdlossy.c"
    "$LIBIJG16_SRC_DIR/jdmainct.c"
    "$LIBIJG16_SRC_DIR/jdmarker.c"
    "$LIBIJG16_SRC_DIR/jdmaster.c"
    "$LIBIJG16_SRC_DIR/jdmerge.c"
    "$LIBIJG16_SRC_DIR/jdphuff.c"
    "$LIBIJG16_SRC_DIR/jdpostct.c"
    "$LIBIJG16_SRC_DIR/jdpred.c"
    "$LIBIJG16_SRC_DIR/jdsample.c"
    "$LIBIJG16_SRC_DIR/jdscale.c"
    "$LIBIJG16_SRC_DIR/jdshuff.c"
    "$LIBIJG16_SRC_DIR/jdtrans.c"
    "$LIBIJG16_SRC_DIR/jerror.c"
    "$LIBIJG16_SRC_DIR/jfdctflt.c"
    "$LIBIJG16_SRC_DIR/jfdctfst.c"
    "$LIBIJG16_SRC_DIR/jfdctint.c"
    "$LIBIJG16_SRC_DIR/jidctflt.c"
    "$LIBIJG16_SRC_DIR/jidctfst.c"
    "$LIBIJG16_SRC_DIR/jidctint.c"
    "$LIBIJG16_SRC_DIR/jidctred.c"
    "$LIBIJG16_SRC_DIR/jmemmgr.c"
    "$LIBIJG16_SRC_DIR/jmemnobs.c"
    "$LIBIJG16_SRC_DIR/jquant1.c"
    "$LIBIJG16_SRC_DIR/jquant2.c"
    "$LIBIJG16_SRC_DIR/jutils.c"
)

cpp_files=(
    # charls
    "$CHARLS_SRC_DIR/version.cpp"
    "$CHARLS_SRC_DIR/charls_jpegls_decoder.cpp"
    "$CHARLS_SRC_DIR/charls_jpegls_encoder.cpp"
    "$CHARLS_SRC_DIR/jpegls.cpp"
    "$CHARLS_SRC_DIR/jpegls_error.cpp"
    "$CHARLS_SRC_DIR/jpeg_stream_reader.cpp"
    "$CHARLS_SRC_DIR/jpeg_stream_writer.cpp"

    "$WASM_SRC_DIR/DecoderContext.cpp"
    "$WASM_SRC_DIR/DecoderParameters.cpp"
    "$WASM_SRC_DIR/Exception.cpp"
    "$WASM_SRC_DIR/Message.cpp"
    "$WASM_SRC_DIR/RleDecoder.cpp"
    "$WASM_SRC_DIR/Jpeg2000EncodedBuffer.cpp"
    "$WASM_SRC_DIR/JpegDecoder.cpp"
    "$WASM_SRC_DIR/JpegDecoder8.cpp"
    "$WASM_SRC_DIR/JpegDecoder12.cpp"
    "$WASM_SRC_DIR/JpegDecoder16.cpp"
    "$WASM_SRC_DIR/NativePixelDecoder.cpp"
)

include_directories=(
    "-I$CHARLS_INCL_DIR"
    "-I$OPENJPEG_SRC_DIR"
    "-I$LIBIJG8_SRC_DIR"
    "-I$LIBIJG12_SRC_DIR"
    "-I$LIBIJG16_SRC_DIR"
)

suppress_warnings=(
    "-Wno-implicit-const-int-float-conversion"
    "-Wno-deprecated-register"
)

definitions=(
  "-DCHARLS_NO_DEPRECATED_WARNING"
)

mkdir -p ./bin
emcc --no-entry -Werror -O3 -std=c++14 \
  "${c_files[@]}" \
  -x c++ "${cpp_files[@]}" \
  "${include_directories[@]}" "${suppress_warnings[@]}" "${definitions[@]}" \
  -s EXPORTED_FUNCTIONS=[] \
  -s EXPORTED_RUNTIME_METHODS=[cwrap] \
  -s TOTAL_MEMORY=256MB \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s DISABLE_EXCEPTION_CATCHING=1 \
  -s FILESYSTEM=0 \
  -o ./bin/native-pixel-decoder.wasm
